homework5
vitaliis-git/cypress-homeworks pull request #1
Opened 2023-05-16 16:10 UTC by vitaliis-git

homework5

2023-05-17 09:46 UTC, SanitarskyiDmytro requested changes

2023-05-17 09:46 UTC, SanitarskyiDmytro commented on cypress/hw-cypress/hw5.cy.js
> +        cy.get('body > ngx-app > ngx-pages > ngx-sample-layout > nb-layout > div > div > div > div > div > nb-layout-column > ngx-form-elements > ngx-form-layouts > div:nth-child(1) > div > nb-card >
потрібно переробити локатор)

.form-inline button

2023-05-18 12:33 UTC, vitaliis-git commented on cypress/hw-cypress/hw5.cy.js
> +        cy.get('body > ngx-app > ngx-pages > ngx-sample-layout > nb-layout > div > div > div > div > div > nb-layout-column > ngx-form-elements > ngx-form-layouts > div:nth-child(1) > div > nb-card >
Дякую, переробив

2023-05-18 15:16 UTC, SanitarskyiDmytro approved these changes

2023-05-30 15:52 UTC, merged